# Generated by Django 4.2.2 on 2023-07-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_ensenanza', models.TextField()),
                ('medios', models.TextField()),
                ('evaluacion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('aporte_tmap', models.TextField()),
                ('requisitos', models.TextField()),
                ('objetivo', models.TextField()),
                ('objetivos_especificos', models.TextField()),
                ('descripcion_producto_academico', models.TextField()),
                ('id_ambiente_aprendisaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambienteaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.TextField()),
                ('horas_docencias', models.IntegerField()),
                ('horas_gestion_practica', models.IntegerField()),
                ('minutos_practicas_docencias', models.IntegerField()),
                ('horas_autonomas', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('producto_parcial', models.TextField()),
                ('resultado_estandares', models.TextField()),
                ('integracion_carreras', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=500)),
                ('objetivo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('clave', models.CharField(max_length=150)),
                ('ruta', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Subcontenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('descri_existencia', models.TextField()),
                ('descri_numero_ejemplares', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='DatosInformativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisitos', models.TextField()),
                ('total_horas_docencia', models.IntegerField()),
                ('total_horas_practicas', models.IntegerField()),
                ('total_horas_docente', models.IntegerField()),
                ('total_horas_autonomas', models.IntegerField()),
                ('horas_trabajos_autonomo', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('coordinador_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_carrera', to='app.trabajador')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asignatura')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidad')),
                ('jefe_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_area', to='app.trabajador')),
                ('responsable1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable1', to='app.trabajador')),
                ('responsable2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable2', to='app.trabajador')),
                ('responsable3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable3', to='app.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='id_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidad'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_producto_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productoacademico'),
        ),
    ]
